import sqlite3
import os

def seed():
    # Ensure the instance folder exists for the database
    if not os.path.exists('instance'):
        os.makedirs('instance')

    conn = sqlite3.connect('instance/names.db')
    cursor = conn.cursor()
    
    # List of tuples format: (Name, Phonetic, Origin)
    names_data = [
        ("Sean", "SHAWN", "Irish"),
        ("Saoirse", "SEER-sha", "Irish"),
        ("Siobhan", "shi-VAWN", "Irish"),
        ("Aoife", "EE-fa", "Irish"),
        ("Niamh", "NEEV", "Irish"),
        ("Cillian", "KILL-ee-an", "Irish"),
        ("Eoghan", "OH-an", "Irish"),
        ("Fionn", "FIN", "Irish"),
        ("Cian", "KEE-an", "Irish"),
        ("Daithi", "DAH-hee", "Irish"),
        ("Aisling", "ASH-ling", "Irish"),
        ("Orlaith", "OR-la", "Irish"),
        ("Tadhg", "TIE-g", "Irish"),
        ("Roisin", "RO-sheen", "Irish"),
        ("Padraig", "PAW-drig", "Irish"),
        ("Xochitl", "SHOW-cheel", "Nahuatl"),
        ("Joaquin", "wah-KEEN", "Spanish"),
        ("Itzel", "EET-zel", "Mayan"),
        ("Citlali", "seet-LAH-lee", "Nahuatl"),
        ("Yaretzi", "yah-RET-see", "Nahuatl"),
        ("Ixchel", "eesh-CHEL", "Mayan"),
        ("Quetzalli", "ket-SAH-lee", "Nahuatl"),
        ("Cuauhtemoc", "KWAU-teh-mok", "Nahuatl"),
        ("Nguyen", "NGWIN", "Vietnamese"),
        ("Phuong", "FOONG", "Vietnamese"),
        ("Quynh", "KWIN", "Vietnamese"),
        ("Thao", "TOW", "Vietnamese"),
        ("Huy", "HWEE", "Vietnamese"),
        ("Minh", "MIN", "Vietnamese"),
        ("Tuan", "TWAHN", "Vietnamese"),
        ("Trinh", "TRIN", "Vietnamese"),
        ("Bich", "BEEK", "Vietnamese"),
        ("Svetlana", "svet-LAH-na", "Slavic"),
        ("Anastasiya", "ah-nah-stah-SEE-ya", "Slavic"),
        ("Yevgeniy", "yev-GEH-nee", "Russian"),
        ("Oleksandr", "oh-lek-SAN-der", "Ukrainian"),
        ("Mykhailo", "mih-KHAI-lo", "Ukrainian"),
        ("Bohdan", "BOHD-an", "Slavic"),
        ("Dmytro", "DMIH-tro", "Ukrainian"),
        ("Zoryana", "zor-YAH-na", "Ukrainian"),
        ("Kateryna", "kah-teh-REE-na", "Ukrainian"),
        ("Sviatoslav", "svyah-toh-SLAHV", "Slavic"),
        ("Bjorn", "BYORN", "Scandinavian"),
        ("Soren", "SUR-en", "Danish"),
        ("Aksel", "ACK-sel", "Scandinavian"),
        ("Freja", "FRAY-ya", "Scandinavian"),
        ("Stig", "STEEG", "Scandinavian"),
        ("Mikkel", "MICK-el", "Danish"),
        ("Jorgen", "YOR-gen", "Scandinavian"),
        ("Kjell", "KYELL", "Norwegian"),
        ("Siavash", "see-ah-VASH", "Persian"),
        ("Kaveh", "kah-VEH", "Persian"),
        ("Mehrdad", "MEHR-dad", "Persian"),
        ("Parisa", "pah-REE-sa", "Persian"),
        ("Shahrzad", "shah-RZAD", "Persian"),
        ("Khosrow", "KHOZ-row", "Persian"),
        ("Behzad", "BEHZ-ad", "Persian"),
        ("Ardeshir", "ar-deh-SHEER", "Persian"),
        ("Farshad", "FAR-shad", "Persian"),
        ("Pouya", "POO-ya", "Persian"),
        ("Roxana", "rok-SAH-na", "Persian"),
        ("Sohrab", "so-HRAB", "Persian"),
        ("Bahram", "bah-HRAHM", "Persian"),
        ("Dariush", "dar-YOOSH", "Persian"),
        ("Jamshid", "jam-SHEED", "Persian"),
        ("Shahin", "shah-HEEN", "Persian"),
        ("Niloofar", "nee-loo-FAR", "Persian"),
        ("Golshifteh", "gol-SHIF-teh", "Persian"),
        ("Ramin", "rah-MEEN", "Persian"),
        ("Navid", "nah-VEED", "Persian"),
        ("Chukwuemeka", "chook-WEH-meh-kah", "Igbo (Nigerian)"),
        ("Oluwadamilola", "oh-loo-wah-dah-MEE-loh-lah", "Yoruba (Nigerian)"),
        ("Babajide", "bah-bah-JEE-day", "Yoruba"),
        ("Adebola", "ah-deh-BOH-lah", "Yoruba"),
        ("Funke", "FOON-keh", "Yoruba"),
        ("Ayodele", "ah-YOH-deh-leh", "Yoruba"),
        ("Yakubu", "yah-KOO-boo", "West African"),
        ("Szymon", "SHI-mon", "Polish"),
        ("Grzegorz", "GZHE-gozh", "Polish"),
        ("Wojciech", "VOY-chekh", "Polish"),
        ("Zbigniew", "ZBIG-nyev", "Polish"),
        ("Czeslaw", "CHEZ-wahv", "Polish"),
        ("Radoslaw", "rah-DOH-swahv", "Polish"),
        ("Bartosz", "BAR-tosh", "Polish"),
        ("Krzysztof", "KRISH-toff", "Polish"),
        ("Caoimhe", "KEE-va", "Irish"),
        ("Eilidh", "AY-lee", "Scottish Gaelic"),
        ("Ruaidhri", "ROO-ree", "Irish"),
        ("Muireann", "MIR-in", "Irish"),
        ("Blathnaid", "BLAH-nid", "Irish"),
        ("Hrafn", "HRAHVN", "Icelandic"),
        ("Gudrun", "GOO-drun", "Norse"),
        ("Eirikr", "AY-rik-er", "Old Norse"),
        ("Thordis", "THOR-dis", "Norse"),
        ("Snaebjorn", "SNYE-byorn", "Icelandic"),
        ("Kazimierz", "kah-ZHEE-myesh", "Polish"),
        ("Przemyslaw", "psheh-MIH-swahv", "Polish"),
        ("Wladyslaw", "vwah-DIH-swahv", "Polish"),
        ("Slawomir", "swah-VOH-meer", "Polish"),
        ("Boguslaw", "boh-GOO-swahv", "Polish"),
        ("Yuliana", "yoo-lee-AH-na", "Slavic"),
        ("Lyubomir", "lyoo-BOH-meer", "Slavic"),
        ("Dobroslav", "DOH-broh-slahv", "Slavic"),
        ("Radomir", "rah-DOH-meer", "Slavic"),
        ("Velimir", "VEH-lee-meer", "Slavic"),
        ("Chinedum", "chee-NEH-doom", "Igbo"),
        ("Nkiru", "NKEE-roo", "Igbo"),
        ("Ifeanyichukwu", "ee-feh-AHN-yee-choo-koo", "Igbo"),
        ("Obinna", "oh-BEEN-nah", "Igbo"),
        ("Uchechukwu", "oo-CHEH-choo-koo", "Igbo"),
        ("Nahuel", "nah-WELL", "Mapuche"),
        ("Lautaro", "low-TAH-roh", "Mapuche"),
        ("Yamila", "yah-MEE-lah", "Spanish (Latin America)"),
        ("Milagros", "mee-LAH-gros", "Spanish"),
        ("Soledad", "soh-leh-DAD", "Spanish"),
        ("Ryosuke", "RYOH-skeh", "Japanese"),
        ("Shunsuke", "SHOON-skeh", "Japanese"),
        ("Takahiro", "tah-kah-HEE-roh", "Japanese"),
        ("Kazuyoshi", "kah-zoo-YOH-shee", "Japanese"),
        ("Yukihiro", "yoo-kee-HEE-roh", "Japanese"),
        ("Xiangyu", "SHYAHNG-yoo", "Chinese"),
        ("Zhixuan", "JER-shwen", "Chinese"),
        ("Qiming", "CHEE-ming", "Chinese"),
        ("Xuefeng", "SHWEH-fung", "Chinese"),
        ("Chunhua", "CHOON-hwah", "Chinese"),
        ("Sukhdeep", "SOOK-deep", "Punjabi"),
        ("Harpreet", "har-PREET", "Punjabi"),
        ("Parminder", "par-MIN-der", "Punjabi"),
        ("Balwinder", "bal-WIN-der", "Punjabi"),
        ("Navjot", "NAV-jot", "Punjabi"),
        ("Vasiliy", "vah-SEE-lee", "Russian"),
        ("Fyodor", "FYOH-dor", "Russian"),
        ("Aleksey", "ah-LEK-say", "Russian"),
        ("Yekaterina", "yeh-kah-teh-REE-nah", "Russian"),
        ("Nadezhda", "nah-DEZH-dah", "Russian"),
        ("Zlatko", "ZLAHT-koh", "South Slavic"),
        ("Tomislav", "TOH-mee-slahv", "South Slavic"),
        ("Dragomir", "DRAH-goh-meer", "South Slavic"),
        ("Radovan", "RAH-doh-van", "South Slavic"),
        ("Milojko", "MEE-loy-koh", "South Slavic")
    ]

    # Clean existing data to avoid duplicates
    cursor.execute("DELETE FROM names")
    
    # Bulk insert the new detailed data
    # (name, phonetic, origin, is_favorite defaults to 0)
    cursor.executemany('''
        INSERT INTO names (name, phonetic, origin, is_favorite) 
        VALUES (?, ?, ?, 0)
    ''', names_data)
    
    conn.commit()
    conn.close()
    print(f"Success! {len(names_data)} names with phonetic details are now in your database.")

if __name__ == "__main__":
    seed()